server:
  port: 8080
spring:
  redis:
    #数据库索引
    database: 0
    host: 172.16.0.126
    port: 6379
    password: 12345
    jedis:
      pool:
        #最大连接数
        max-active: 8
        #最大空闲
        max-idle: 8
        #最小空闲
        min-idle: 0
        #连接超时时间
        timeout: 10000
  datasource:
    url: jdbc:mysql://172.16.0.75:3306/luna?serverTimezone=GMT%2B8&characterEncoding=UTF-8&allowMultiQueries=true
    username: wangfangrui
    password: 19921027wang
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#logging:
#  file: info.log
#  level:
#    root: warn